name: vps-deploy

on:
  pull_request:
    types: [closed]
    branches: [ master ]

jobs:

  update-repo:
    runs-on: ubuntu-latest
    env:
      BACK_END_TRIGGER: ${{ secrets.BACK_END_TRIGGER }}
      WEB_TRIGGER: ${{ secrets.WEB_TRIGGER }}

    steps:
      - name: pr Title
        run: echo "${{ github.event.pull_request.title }}"
      - name: Title BACK
        if: ${{ startsWith( github.event.pull_request.title , env.BACK_END_TRIGGER ) }}
        run: echo "BACK PR"
      - name: Title WEB
        if: ${{ startsWith( github.event.pull_request.title , env.WEB_TRIGGER ) }}
        run: echo "WEB PR"