name: vps-deploy

on:
  pull_request:
    types: [closed]
    branches: [ master ]

jobs:

  update-repo:
    runs-on: ubuntu-latest

    steps:
      - name: pr Title
        run: echo "${{ github.event.pull_request.title }}"
      - name: Title BACK
        run: echo "${{ env.BACK_END_TRIGGER }}"
      - name: Title CLIENT
        run: echo "${{ env.CLIENT_TRIGGER }}"