name: vps-deploy

on:
  pull_request:
    types: [closed]
    branches: [ master ]

jobs:

  update-back:
    runs-on: ubuntu-latest
    if: ${{ startsWith( github.event.pull_request.title , secrets.BACK_END_TRIGGER ) }}
    steps:
      - name: Title BACK
        run: echo "BACK PR"

  update-web:
    runs-on: ubuntu-latest
    if: ${{ startsWith( github.event.pull_request.title , secrets.BACK_END_TRIGGER ) }}
    steps:
      - name: Title WEB
        run: echo "WEB PR"